name: Run Python Scripts

on: [push]

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.7  # Replace with your required Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 html5lib htmlmin

    - name: Run add_html_extension.py
      run: python scripts/add_html_extension.py

    - name: Run test_links.py
      run: python scripts/test_links.py

    - name: Run format_files.py
      run: python scripts/format_files.py