name: Update Production Branch

on:
  push:
    branches:
      - development

jobs:
  update-production:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout development branch
      uses: actions/checkout@v2
      with:
        ref: development

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Create or update production branch
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git checkout -B production
        git rm -r .github
        git rm -r scripts
        git commit -m "Update production branch"
        git push https://x-access-token:${GH_PAT}@github.com/charbel30/CharbelTannous-portfolio.git production --force